name: griffin-profiling
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pyyaml
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - libstdcxx-ng
  - libgcc-ng
  - pytorch
  - pytorch_geometric
  - pytorch_scatter
  - pip:
      - accelerate
      - datasets
      - evaluate
      - sentence_transformers
      - einops
      - torchmetrics
      - tensorboard
      - safetensors
      - pqdm